version: '3.5'

networks:
  zbx_net_frontend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  snmptraps:
  grafana-data:

services:
  zabbix-server:
    image: docker.io/zabbix/zabbix-server-mysql:alpine-6.0-latest
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dados/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./dados/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./dados/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
      - ./dados/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./dados/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./dados/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./dados/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./dados/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - snmptraps:/var/lib/zabbix/snmptraps:rw
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ZBX_ENABLE_SNMP_TRAPS=true
    depends_on:
      - mysql-server
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-server
          - zabbix-server-mysql
          - zabbix-server-ubuntu-mysql
          - zabbix-server-mysql-ubuntu
      zbx_net_frontend:
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    labels:
      com.zabbix.description: "Zabbix server with MySQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-server"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "ubuntu"

  zabbix-web-nginx-mysql:
    image: docker.io/zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dados/etc/ssl/nginx:/etc/ssl/nginx:ro
      - ./dados/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_NAME=Composed installation
    depends_on:
      - mysql-server
      - zabbix-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      zbx_net_backend:
        aliases:
        - zabbix-web-nginx-mysql
        - zabbix-web-nginx-ubuntu-mysql
        - zabbix-web-nginx-mysql-ubuntu
      zbx_net_frontend:
    stop_grace_period: 10s
    sysctls:
    - net.core.somaxconn=65535
    labels:
      com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-frontend"
      com.zabbix.webserver: "nginx"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "ubuntu"

  zabbix-snmptraps:
    image: docker.io/zabbix/zabbix-snmptraps:alpine-6.0-latest
    ports:
      - "162:1162/udp"
    volumes:
      - snmptraps:/var/lib/zabbix/snmptraps:rw
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      zbx_net_frontend:
        aliases:
        - zabbix-snmptraps
      zbx_net_backend:
    stop_grace_period: 5s
    labels:
      com.zabbix.description: "Zabbix snmptraps"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "snmptraps"
      com.zabbix.os: "ubuntu"

  zabbix-web-service:
    image: docker.io/zabbix/zabbix-web-service:alpine-6.0-latest
    profiles:
      - all
    ports:
       - "10053:10053"
    volumes:
      - ./dados/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
    security_opt:
     - seccomp:./env_vars/chrome_dp.json
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - ZBX_ALLOWEDIP=zabbix-server
    networks:
      zbx_net_backend:
        aliases:
        - zabbix-web-service
        - zabbix-web-service-ubuntu
    stop_grace_period: 5s
    labels:
      com.zabbix.description: "Zabbix web service"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "web-service"
      com.zabbix.os: "ubuntu"

  mysql-server:
    image: docker.io/mysql:8.0-oracle
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --default-authentication-plugin=mysql_native_password
    #   - --require-secure-transport
    #   - --ssl-ca=/run/secrets/root-ca.pem
    #   - --ssl-cert=/run/secrets/server-cert.pem
    #   - --ssl-key=/run/secrets/server-key.pem
    volumes:
      - ./dados/var/lib/mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    stop_grace_period: 1m
    networks:
      zbx_net_backend:
        aliases:
        - mysql-server
        - zabbix-database
        - mysql-database

  zabbix-agent:
    image: docker.io/zabbix/zabbix-agent2:alpine-6.0-latest
    profiles:
      - all
    ports:
     - "10050:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dados/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./dados/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./dados/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./dados/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
      mode: global
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_HOSTNAME=agent-host
    privileged: true
    pid: "host"
    networks:
      zbx_net_backend:
        aliases:
        - zabbix-agent
        - zabbix-agent-passive
        - zabbix-agent-ubuntu
    stop_grace_period: 5s
    labels:
      com.zabbix.description: "Zabbix agent"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-agentd"
      com.zabbix.os: "ubuntu"
      
  grafana:
    image: docker.io/grafana/grafana:latest
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      zbx_net_backend:
        aliases:
        - grafana-server
      zbx_net_frontend:
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      
  db_data_mysql:
    image: docker.io/busybox
    volumes:
      - ./dados/var/lib/mysql:/var/lib/mysql:rw
